[package]
name = "gm_fontsx"
authors = ["Earu"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = { version = "*", default-features = false, features = ["gmcl"] }
font-loader = "0.11.0"